version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: naga_db
    environment:
      POSTGRES_USER: nagauser
      POSTGRES_PASSWORD: nagapass
      POSTGRES_DB: nagadb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
